### PR TITLE
Web Interface Module List

### PR DESCRIPTION
**Pull request by afk**
## Description
Module list added to web interface

## How Has This Been Tested?
Ran on Ubuntu 18.04, tested on Google Chrome 74.0.3729.131

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Web Interface Module List](https://trello.com/c/kTfAazL0/44-web-interface-module-list)

**Review by orhun — APPROVED** [review]
It's OK for now :100:

**Comment by orhun** [comment]
Oh, maybe we can use `inspect` module for getting doc from function.

**Review by furk4nyuksel — APPROVED** [review]
Outside the space looks nice

**Comment by afk** [comment]
> Oh, maybe we can use `inspect` module for getting doc from function.

https://github.com/grapheneX/grapheneX/pull/40/commits/4deb55aad7acbc26376d59039d28d01b90bf1e68
Yeah, that would be better for a cleaned docstring, changed `__doc__` to `inspect.getdoc`.

**Review by bufgix — APPROVED** [review]
👍

**Pull request merged**
