### PR TITLE
Framework Features for CLI & Improvements

### PR DESCRIPTION
**Pull request by orhun**
## Description

* Fix logs bug which caused by multiple event declarations bf8c38e 
* Change 'add module' button size f0485be
* `web` command added for starting the web server from CLI 58a04ac
* Execute OS commands in abstract class (`core/hrd/exec.py`) 7679b73 ~ #43 
* Update pipenv related files for new dependency (`pyinquirer`)
* `manage` command (add, edit, delete) [`#157`](https://github.com/grapheneX/grapheneX/compare/dev...KeyLo99:dev#diff-1a468161d7a1f2de5d5395d5121cf03dR157)
* Unused classes and functions removed.
* Refactor...

## Motivation and Context

Changes are required for us to move on to project. (And of course they are awesome!)

## How Has This Been Tested?

~ Arch Linux

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Interactive Shell <web()>](https://trello.com/c/JDXYILsZ/54-interactive-shell-web)

**Comment by orhun** [comment]
[Add Modules With "add" Command](https://trello.com/c/wqB1QZh7/55-add-modules-with-add-command)

**Comment by bufgix** [comment]
ops
image

**Comment by orhun** [comment]
> ops
> image

https://github.com/magmax/python-inquirer/issues/54

We should find an alternative for this library and implement it to the code... Not that hard since the other parts are working (at least for me, probably work for you guys too)

**Review by bufgix — APPROVED** [review]

**Review by afk — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]

**Review by EnesOkutan — APPROVED** [review]

**Comment by EnesOkutan** [comment]
Looks good but in the future the code can be cleared a little more. 👍

**Pull request merged**
