### PR TITLE
Added help feature

### PR DESCRIPTION
**Pull request by EnesOkutan**
## Description

Methods related to help in the cmd module have been overridden. In this way commands and descriptions are shown when command "help" is given. In addition, the created help.py file is used to display syntax and descriptions of the commands.

## Motivation and Context
Some methods within the cmd module have been overridden in the override class.
Syntax and description representations are provided.

## How Has This Been Tested?
Using the "help" command, the desired output was observed.
Using the "help switch" command, it was observed whether the details about the "switch" command were reached.
## Screenshots (if appropriate):
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by EnesOkutan** [comment]
image

The docstring description is shown in the "help" command.

in that:

image

**Comment by EnesOkutan** [comment]
The descriptions in the commands containing the details are specified in the help.py file (such as "help switch").

In that:

image

**Review by bufgix — CHANGES_REQUESTED** [review]
I told the reason in the Telegram group

**Comment by orhun** [comment]
Do we seriously need override class for overriding the methods? Is it necessary?

**Comment by EnesOkutan** [comment]
No, I think it may be more regular in this way, but we can discuss this, I'm not sure.

**Comment by orhun** [comment]
[Interactive Shell ~ Help Feature](https://trello.com/c/OFpBklar/18-interactive-shell-help-feature)

**Pull request closed without merging**
