### PR TITLE
Web Interface Namespace List

### PR DESCRIPTION
**Pull request by EnesOkutan**
## Description
Server and client side socket connections created.

## Motivation and Context
it was necessary for listening to client side events and retrieving the corresponding module list from the server when namespace changed.

## How Has This Been Tested?
Tested on arch linux.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Web Interface Namespace List](https://trello.com/c/g7OC9wVy/43-web-interface-namespace-list)

**Comment by orhun** [comment]
First of all I don't understand why you try to connect to server again on page load. [#l2](https://github.com/grapheneX/grapheneX/pull/41/files#diff-17e124f1e83ee26dbe78851c012c403bR2) It can be handled with calling `onNamespaceSelected` function at [#l45](https://github.com/grapheneX/grapheneX/pull/41/files#diff-17e124f1e83ee26dbe78851c012c403bR45) And remove the `socketio` variable from that function as well.
Also you can implement #40 for module listing on the DropDown event.
Rest of it is OK.

**Comment by EnesOkutan** [comment]
should I pass the modules I get into the template via javascript or should I render it directly.

**Comment by orhun** [comment]
> should I pass the modules I get into the template via javascript or should I render it directly.

You can render it directly like it's done at #40 if I understand your question correctly.

**Comment by orhun** [comment]
Can we send just the namespaces other than the full module list?

**Comment by orhun** [comment]
> Can we send just the namespaces other than the full module list?

Oh, it's OK like that.
Because we are already sending the `modules` right now. We can merge this PR if you edit your code according to the #40

**Pull request closed without merging**
