### PR TITLE
Created win/exec.py

### PR DESCRIPTION
**Pull request by EnesOkutan**
Exec.py file was created under the win directory for commands that should be executed by command prompt on Windows.

## Description
Some commands need to be run on the command prompt. For this, the exec.py file is created under the win directory.

## Motivation and Context
It allows the execution of the hardening commands that should be executed by the command prompt on Windows.

## How Has This Been Tested?
It has been examined whether it gives the correct output using any cmd command.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bufgix** [comment]
Better to use `subprocess`

```python
import subprocess

def run_cmd(cmd:str) -> str:
    # create process
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
    
    # Run cmd and return output
    return proc.communicate()[0]
```

**Comment by EnesOkutan** [comment]
> Better to use `subprocess`
> 
> ```python
> import subprocess
> 
> def run_cmd(cmd:str) -> str:
>     # create process
>     proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
>     
>     # Run cmd and return output
>     return proc.communicate()[0]
> ```

Special characters are not resolved (\n, \r etc.):

for example: 

>print(run_cmd('dir'))

>Directory of C:\\Users\\Enes\\Desktop\r\n\r\n04/02/2019  01:27 AM    <DIR>          .\r\n04/02/2019  >01:27 AM    <DIR>          ..\r\n03/30/2019  03:42 PM            81,422 adli-sicil-kaydi.pdf\r\n03/29/2019  >11:21 AM    <DIR>          Artificial Intelligence\r\n03/26/2019  12:41 PM         1,082,899 cv->d\x94n\x81st\x81r\x81ld\x81.docx\r\n03/27/2019  10:34 AM           734,720 cv1 (1).docx\r\n03/15/2019  >01:47 AM         1,193,481 cv1.pdf\r\n04/02/2019  02:29 AM                57 deneme.py\r\n04/01/2019  >01:01 PM    <DIR>          dev\r\n04/01/2019  12:36 PM    <DIR>          Ergonomilm\r\n04/01/2019  >12:40 PM        83,381,588 Ergonomilm.rar\r\n03/30/2019  04:16 PM            58,178 >fotograf.png\r\n04/02/2019  12:16 AM    <DIR>          grapheneX\r\n12/05/2016  07:33 PM         >6,914,376 idman626build14.exe\r\n03/27/2019  10:44 AM             1,078 Internet Download >Manager.lnk\r\n03/30/2019  03:37 PM            66,924 kimlik_fotokopi.pdf\r\n04/01/2019  12:36 PM    >><DIR>          main\r\n04/01/2019  12:43 PM         5,574,185 main.rar\r\n03/26/2019  04:45 PM             >1,446 Microsoft Edge.lnk\r\n03/31/2019  01:24 AM    <DIR>          New\r\n03/31/2019  12:08 AM    >>><DIR>          New folder\r\n12/15/2017  07:25 PM       755,530,376 officesp2010-kb2687455-fullfile->x64-tr-tr.exe\r\n03/30/2019  09:57 PM    <DIR>          proje\r\n03/30/2019  03:27 PM           529,566 >TapScanner_20190330_151716_87.jpg\r\n04/01/2019  07:18 PM             1,029 >Telegram.lnk\r\n04/01/2019  11:44 PM                 4 test\r\n04/01/2019  10:11 PM               414 >test.py\r\n04/02/2019  02:43 AM               246 tests.py\r\n03/30/2019  03:47 PM           107,552 >transkript.pdf\r\n03/30/2019  04:01 PM            91,122 Zorunlu-staj-belgesi.pdf\r\n              20 File(s)    >855,350,663 bytes\r\n              10 Dir(s)  290,130,837,504 bytes free\r\n'

provides a jumble image, it needs to be resolved.

**Comment by bufgix** [comment]
This is not problem. 
```python
import subprocess

def run_cmd(cmd:str) -> str:
    # create process
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
    
    # Run cmd and return output
    return proc.communicate()[0].decode("utf-8").strip()
```

But I haven't tested on Windows. Can you test it?

**Comment by EnesOkutan** [comment]
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 364: invalid start byte`

This gives the error. I've run a lot of similar code, but the same errors occur.
I think the problem may be caused by my computer. Can someone try this code?

**Comment by bufgix** [comment]
its seems use `os.system()` is best way.

**Review by bufgix — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]
this looks fine

**Review by bufgix — APPROVED** [review]

**Comment by orhun** [comment]
[[Windows] Command Execute Class](https://trello.com/c/CDebYiGd/7-windows-command-execute-class)

**Review by afk — APPROVED** [review]

**Review by orhun — APPROVED** [review]

**Pull request merged**
