### PR TITLE
Back command added for go back.

### PR DESCRIPTION
**Pull request by EnesOkutan**
Added back command to enable navigation in command interface.

## Description
The command interface navigation is provided by adding the back command into commands.py.

## Motivation and Context
Reversals within the command interface were not defined. This is designed to enable reversals.

## How Has This Been Tested?
Tested on Windows.
Modules and namespaces are selected and the back command is tested.
It has been tested whether this back command is functional or not.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by kalaycitayfun — APPROVED** [review]

**Comment by orhun** [comment]
[Interactive Shell <back()>](https://trello.com/c/K17H99CD/26-interactive-shell-back)

**Review by furk4nyuksel — APPROVED** [review]

**Review by orhun — CHANGES_REQUESTED** [review]
Your code looks nice and convenient.
But I'm not totally sure we need split functions. And this solution does not work with `use logs_restrict_access` command for example. Because it's designed to check namespace first. It can be solved quickly.
But after little bit of sticking around the code I can come up with a easier solution:

```
if self.module:
    self.module = ""
else:
    self.namespace = ""
```
Please test this out and evaluate.

**Comment by EnesOkutan** [comment]
If more than one sub-namespace is not selected or if there is no hierarchical selection of multiple modules within these namespaces, this is more convenient.

**Comment by orhun** [comment]
> If more than one sub-namespace is not selected or if there is no hierarchical selection of multiple modules within these namespaces, this is more convenient.

I think we are not planning to integrate multiple module selection support for now.
If things will change in the future, we can use your code anyway.

**Review by orhun — APPROVED** [review]

**Comment by EnesOkutan** [comment]
[test](https://trello.com/c/IFLtIctN/1-test)

**Pull request merged**
