### PR TITLE
Info method added.

### PR DESCRIPTION
**Pull request by kalaycitayfun**
## Description

Show info about the hardening method. 

## How Has This Been Tested?

Win10 tested. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Interactive Shell <info()>](https://trello.com/c/sCyYzG6O/23-interactive-shell-info)

**Review by orhun — APPROVED** [review]
It might be improved but it's OK for now.

**Review by afk — APPROVED** [review]

**Comment by EnesOkutan** [comment]
There is an error:

`[gX]> use Logs_Restrict_Access
17:30:53 > core.cli.commands > INFO > "Logs_Restrict_Access" module selected. Use 'harden' command for hardening or use 'info' for more information.
[gX:Logs_Restrict_Access]> info
Traceback (most recent call last):
  File "grapheneX.py", line 19, in <module>
    main()
  File "grapheneX.py", line 14, in main
    shell.cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/leohuntera/grapheneX/grapheneX/core/cli/commands.py", line 63, in do_info
    print(self.modules[self.namespace][self.module]().command.__doc__)
KeyError: ''
`

error occurs when module is selected without selecting namespace.

For example: 

use Logs_Restrict_Access
info

occurs error.

**Comment by EnesOkutan** [comment]
By checking that the namespace is entered, you need to take action according to this control.

**Review by EnesOkutan — APPROVED** [review]
Looks, fine !

**Pull request merged**
