### PR TITLE
added commands.py and moved shell commands to commands.py

### PR DESCRIPTION
**Pull request by bufgix**
## Description
Shell commands moved to `ShellCommands()` class in `commands.py`

## How Has This Been Tested?
Tested on Windows

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Looks good to me. But may I ask, is this code correct according to PEP8?
Because I saw extra spaces and newlines somewhere. If it is okay, means that I should work on PEP8 much more :/

**Comment by bufgix** [comment]
> Looks good to me. But may I ask, is this code correct according to PEP8?
> Because I saw extra spaces and newlines somewhere. If it is okay, means that I should work on PEP8 much more :/


Fixed https://github.com/grapheneX/grapheneX/pull/15/commits/c09a4a380524ed2e2f22255002407dcd1d4a5aee

**Review by EnesOkutan — APPROVED** [review]
Congratulations, much better.

**Review by orhun — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]

**Comment by orhun** [comment]
[Interactive Shell Commands](https://trello.com/c/F9MxCdIB/16-interactive-shell-commands)

**Pull request merged**
