### PR TITLE
ci: Add automated docker builds

### LINKED ISSUE #156: Set up automated Docker builds
**Is your feature request related to a problem? Please describe.**

Docker builds are not automated so we don't know if the image is building fine or not. See #155 

**Describe the solution you'd like**

Create a new GitHub Actions file for building the image (and potentially pushing it to DockerHub / GitHub registry).

**Describe alternatives you've considered**

None.

**Additional context**

We can probably adopt this from another project such as: https://github.com/orhun/halp/blob/main/.github/workflows/docker.yml

### PR DESCRIPTION
**Pull request by jvirgovic**
## Description

Automated docker build, push to GHCR / DH.
Secrets need to be setup in gX github repo 4 this to work correctly.

## Motivation and Context

As we've seen in #155 there's no way of knowing if the docker builds correctly, now with this CI it should be fixed.
Closes #156.

## How Has This Been Tested?

n/a

## Screenshots (if appropriate):
n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Thanks for the PR! The job is failing, can you look into it?

**Comment by jvirgovic** [comment]
Hmm, Is the DockerHub username / token correct? Maybe the token doesn't have proper permissions?

**Comment by orhun** [comment]
Yeah, they are correct. Not sure if any permissions are needed since the image build step fails for some reason :/

**Comment by jxdv** [comment]
Now it fails in the image scanning phase xD Interesting. I am trying to figure out what's wrong

**Comment by jxdv** [comment]
@orhun I think It's failing since gX is not yet available on GHCR and therefore:
```/opt/hostedtoolcache/syft/0.84.0/x64/syft packages -vv ghcr.io/grapheneX/grapheneX -o spdx-json```
Will just exit with code 1.

**Comment by jxdv** [comment]
Works now, but without the image scanning :/

**Comment by jvirgovic** [comment]
@orhun, The pipeline is failing here:
`/opt/hostedtoolcache/syft/0.84.0/x64/syft packages -vv ghcr.io/grapheneX/grapheneX -o spdx-json`
I am not very knowledgeable about GHCR, but I assume that since gX is not yet uploaded there, the syft tool fails to get the json output and exits with code 1.

I've rewritten the docker.yml file completely using your already existing one from [halp](https://github.com/orhun/halp/blob/main/.github/workflows/docker.yml), but still no success :/

**Review by orhun — APPROVED** [review]
Removed the SBOM and provenance and now it is looking good! Thanks for your patience/efforts on this 🐻

**Pull request merged**
