### PR TITLE
Added switch and search commands

### PR DESCRIPTION
**Pull request by bufgix**
## Description
These commands can search and explore in available modules. For more information check comments lines.

## How Has This Been Tested?
Tested on Windows

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bufgix** [comment]
[Interactive Shell <switch()>](https://trello.com/c/eE2tACcP/25-interactive-shell-switch)

**Comment by bufgix** [comment]
[Interactive Shell <search()>](https://trello.com/c/wg0bYhcv/21-interactive-shell-search)

**Comment by orhun** [comment]
[Interactive Shell <switch()>](https://trello.com/c/eE2tACcP/25-interactive-shell-switch)

**Review by EnesOkutan — APPROVED** [review]
Looks fine

**Review by furk4nyuksel — APPROVED** [review]
I like this good job

**Comment by orhun** [comment]
Are you planning to improve this code in the near future? It looks like we're not going to merge this since there is some unclear parts in your code and this causes more conflicts than expected.

**Pull request closed without merging**
