### PR TITLE
Web Interface & Argparser

### PR DESCRIPTION
**Pull request by EnesOkutan**
## Description
If the -w argument is entered, the web server will be executed with the given host and port parameters or default values

## Motivation and Context
To start the web server, the -w argument had to be captured.
The optional host and port address needed to be specified if the user wanted to work on a different host or port.

## How Has This Been Tested?
Tested on Windows 10 and Arch Linux

## Screenshots (if appropriate):
image

image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
It looks like it's not starting the CLI if -w argument is given. (Haven't tested the code) We should design the project for using the both I think.

**Comment by EnesOkutan** [comment]
hmm, Do I need to start the cli when the web interface starts?

**Comment by orhun** [comment]
> hmm, Do I need to start the cli when the web interface starts?

Yes, we have to. 
Also there's some issues caught my eye on your code that can be refactored but I think we can fix those issues later. (Not that important for now)

**Comment by orhun** [comment]
[Web Interface & Argparser](https://trello.com/c/pDPHnOFQ/37-web-interface-argparser)

**Comment by orhun** [comment]
Okay I take my word back. It's better to run server without CLI. Revert it back and I'll approve.

**Review by kalaycitayfun — APPROVED** [review]

**Review by orhun — APPROVED** [review]
:+1:

**Review by bufgix — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]

**Review by afk — APPROVED** [review]

**Pull request merged**
