### PR TITLE
feat: Add require restart

### LINKED ISSUE #131: Restarting services to apply changes
Hi, I am not sure about Windows, but a lot of these hardening changes actually require to restart services for the changes to take place (either this or reboot).

For example:
- To load some of the network changes, we would need to: sudo sysctl -p
- To apply changes to the sshd_config: sudo service ssh restart
etc...

You get my point; Perhaps it would make sense to add another key to modules.json: "require_restart", or atleast somehow inform the user that the changes will aply after they restart the service themselves, or this can be implemented.

LMK What you think about this. I could add this If you'd be interested, also I'd like to add that this project is really amazing, and you've done a very good job!

### PR DESCRIPTION
**Pull request by jvirgovic**
## Description

Added 'require_restart' key to modules.json.

## Motivation and Context

Closes #131.
Currently we can execute a hardening module, but how do we really know that the changes have been applied? We don't.
The solution is to add the 'require_restart' field, which will give a hint to the user.

Yes, there are no 'restart' commands provided, because if the user is hardening (for example) SSHD config, than he should know that all he has to do is google: 'restart sshd config'

## How Has This Been Tested?

It works correctly on both Web UI and CLI.
CLI tested:
- add new module
- edit module
- remove module
- run module

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jvirgovic** [comment]
@orhun Would you also be able to update the 'all-contributors' since I've changed my GH username: jxd1337 -> jxdv
so the links won't be broken anymore; Thanks!

**Comment by jvirgovic** [comment]
If you approve & merge, I'll prepare for a new release.
I also need to go through all the commands (except for SSH) and see if they need to be restarted to correctly adjust the value.

**Comment by orhun** [comment]
> update the 'all-contributors'

I removed allcontributors in d6d8195092378af685c6b5b51f179f570cbaf88b since it is an additional maintenance burden.

> If you approve & merge, I'll prepare for a new release.

Sounds good, thanks a lot!

**Review by orhun — APPROVED** [review]
Tested, works well!

**Pull request merged**
