### PR TITLE
Web Page & Libraries

### PR DESCRIPTION
**Pull request by bufgix**
## Description
Created html draft. Added socket.io, bootstrap and jquery.

## How Has This Been Tested?
Tested on Windows 10

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by orhun — APPROVED** [review]

**Comment by orhun** [comment]
:+1:

**Review by furk4nyuksel — APPROVED** [review]
Looks Good

**Comment by EnesOkutan** [comment]
👍

**Review by EnesOkutan — APPROVED** [review]

**Comment by orhun** [comment]
[Web Interface Front-End Draft](https://trello.com/c/ev7Nc8oD/38-web-interface-front-end-draft)

**Pull request merged**
