### PR TITLE
switch & use & list commands [CLI]

### PR DESCRIPTION
**Pull request by orhun**
## Description

`switch` -> switch between namespaces
`use` -> select hardening module
`list` -> list hardening modules

Other changes are:
* Improve `search` command (asciitables added, moved `get_modules` to `core/utils/helpers.py`)
* `core/cli/shell.py` improved for switching modules
* Fix some print messages in `core/cli/help.py`
* Help methods added for new commands
* more...

Example usages:
```
switch kernel
list
use logs_restrict_access
```
```
use logs_restrict_access
```
```
use kernel/logs_restrict_access
```

## Motivation and Context

Changes are required due to the need of traversing modules and namespaces.

## How Has This Been Tested?

GNU/Linux

## Screenshots (if appropriate):
PR23

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Interactive Shell <switch()>](https://trello.com/c/eE2tACcP/25-interactive-shell-switch)

**Comment by orhun** [comment]
[Interactive Shell <use()>](https://trello.com/c/WdvQLZsv/22-interactive-shell-use)

**Comment by orhun** [comment]
[Interactive Shell <list()>](https://trello.com/c/27Q1D1rQ/29-interactive-shell-list)

**Review by bufgix — APPROVED** [review]

**Review by afk — APPROVED** [review]

**Comment by bufgix** [comment]
Test

**Review by EnesOkutan — APPROVED** [review]
It works. It's in good shape.

**Pull request merged**
