### PR TITLE
Added superclass for hardening classes

### PR DESCRIPTION
**Pull request by bufgix**
## Description
Added superclass(`HardenMethod`). Hardening classes must inheritance this class

## Motivation and Context
My aim, collect common properties in hardening class to super class

## How Has This Been Tested?
Tested on Windows 10

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
@bufgix Does it support harden() command?

**Comment by bufgix** [comment]
> @bufgix Does it support harden() command?

yup

**Comment by EnesOkutan** [comment]
Now much better, Congratulations !

**Review by EnesOkutan — APPROVED** [review]

**Review by orhun — APPROVED** [review]
:+1:

**Review by kalaycitayfun — APPROVED** [review]

**Pull request merged**
