### PR TITLE
ci: PyPI edit tag pattern

### PR DESCRIPTION
**Pull request by jvirgovic**
## Description

Fixed tag in publish.yml

## Motivation and Context

It should trigger correctly now on a new tag creation.

## How Has This Been Tested?

n/a

## Screenshots (if appropriate):
n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
I don't think this is correct, we don't use `v` prefix with the tags:

```
$ git tag
1.0.1
1.1.0
1.1.1
1.1.2
1.1.3
1.2.0
1.2.1
1.2.2
1.3.0
1.3.1
1.3.2
```

**Comment by jvirgovic** [comment]
I got confused I guess since the github releases follow the "v*.*.*" pattern

**Comment by orhun** [comment]
Can we somehow test this to make sure it works?

**Comment by jvirgovic** [comment]
Unfortunately I don't think so. Just by pushing a new release, but I think that this should definitely fix it.

**Comment by orhun** [comment]
I have tested this [in my fork](https://github.com/orhun/grapheneX/releases) and fixed in 4ed2dc3e412e4c9267a59bdac45e62e6242d67ea

The problem was `push` was missing and the tag pattern was wrong. It works now and we're ready for a new release 🐻 

Thanks for bearing with me on this :D Closing.

**Pull request closed without merging**
