### PR TITLE
exec.py improved

### PR DESCRIPTION
**Pull request by afk**
## Description

You can now pass any kwarg to `subprocess.run`

## Motivation and Context

Previously you didn't have much control over `subprocess.run`. Now you can pass any argument you want.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by EnesOkutan** [comment]
This does not work in Windows,
In Windows to work, the shell parameter must be True. But in this case also `UnicodeDecodeError` occurs

**Comment by orhun** [comment]
> This does not work in Windows,
> In Windows to work, the shell parameter must be True. But in this case also `UnicodeDecodeError` occurs

This does not have to work on Windows since it's the `core/linux/exec.py`

**Review by orhun — APPROVED** [review]
Looks appropriate :+1:

**Review by EnesOkutan — APPROVED** [review]
This is a good change

**Review by furk4nyuksel — APPROVED** [review]
look good

**Review by bufgix — APPROVED** [review]

**Pull request merged**
