### PR TITLE
Merge branch 'dev' into master (v1.0.1)

### PR DESCRIPTION
**Pull request by orhun**
## Description

1.0.1 release

## Motivation and Context

`dev` branch should be merged into `master` since the development process of v1.0.1 is over.

## How Has This Been Tested?

~

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by bufgix — APPROVED** [review]
Yaaay

**Comment by orhun** [comment]
@all-contributors please add @KeyLo99 for code, doc, projectManagement, question, ideas, review

**Comment by orhun** [comment]
@all-contributors please add @bufgix for code, design, platform, ideas, review

**Comment by orhun** [comment]
@all-contributors please add @EnesOkutan for code, ideas, review

**Comment by orhun** [comment]
@all-contributors please add @afk for code, ideas, review

**Comment by orhun** [comment]
@all-contributors please add @ibanez75612 for code, platform, review

**Comment by orhun** [comment]
@all-contributors please add @emperorfederico for code

**Pull request merged**
