### PR TITLE
refactor: edit codebase according to PEP

### PR DESCRIPTION
**Pull request by jvirgovic**
## Description
- remove unused import
- format strings / args to comply with PEP
- change bare except clauses
- change certain doc-strings
- add new-line at the end of file
- change do_exit to staticmethod

### CODE REVIEW

**Comment by orhun** [comment]
Let's wait for #149 before merging this.

**Comment by jvirgovic** [comment]
Good, I'll prepare to release v1.4.1 after these 2 PRs get merged.

**Comment by orhun** [comment]
Sounds good!

**Comment by orhun** [comment]
Can you rebase the changes from `master`?

**Comment by jvirgovic** [comment]
done

**Comment by orhun** [comment]
Can you look into linter errors reported by CI?

**Comment by jvirgovic** [comment]
Yes, I'll fix all of those and ping you once it's ready for merging

**Comment by orhun** [comment]
Great, thanks!

**Comment by jvirgovic** [comment]
I'll edit the linter to stop screaming if the line is longer than 79 chars. I'll make 120 a new maximum which is much more acceptable IMO

**Comment by jvirgovic** [comment]
@orhun ready for final review

**Review by orhun — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
