### PR TITLE
Logging Class

### PR DESCRIPTION
**Pull request by bufgix**
## Description
Logger for Graphenex Project
```pycon
>>>logger = GraphenexLogger("graphenex.main", level="DEBUG")
>>>logger.debug("This is a debug message")
01:36:35 > graphenex.main > DEBUG > This is a debug message
>>>logger.info("Cool information message")
01:36:35 > graphenex.main > INFO> Cool information message
```
`GraphenexLogger(name, level, format)`

## How Has This Been Tested?
Tested Windows and Linux system

## Screenshots (if appropriate):
sc
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kalaycitayfun — APPROVED** [review]

**Comment by bufgix** [comment]
Opss, i forgot to change the requirement.txt. I'll fix that

**Comment by KeyLo99** [comment]
It looks good to me :+1:

**Comment by KeyLo99** [comment]
Looks good to me

**Comment by afk** [comment]
test

**Comment by orhun** [comment]
It looks good to me :+1:

**Review by orhun — APPROVED** [review]

**Comment by orhun** [comment]
[Logging Class](https://trello.com/c/LVaGl9vL/4-logging-class)

**Review by furk4nyuksel — COMMENTED** [review]
good

**Review by afk — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]
is okey

**Comment by bufgix** [comment]
[Format attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes) for effective usage.

**Comment by KeyLo99** [comment]
[test]

**Review by furk4nyuksel — APPROVED** [review]

**Review by furk4nyuksel — APPROVED** [review]

**Pull request merged**
