### PR TITLE
Project Refactor I

### PR DESCRIPTION
**Pull request by orhun**
## Description

Most of the classes refactored, necessary comment lines added and fixed PEP8 issues.
Includes:
* Updated ASCII logo.
* Creating `core/utils` directory.
* `core/win/editreg.py` refactor (+ code fixes) and comments.
* `core/utils/argparser.py` refactor
* and more.

## Motivation and Context

This changes with this PR are required for us to move on.

## How Has This Been Tested?

Linux.
I've changed the `core/win/editreg.py` without testing. Hope it's working. (There was syntax issues)
I'd be appreciated if someone test this class.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
[Project Refactor (I)](https://trello.com/c/35jkFm6N/13-project-refactor-i)

**Review by bufgix — APPROVED** [review]
That's better :+1:

**Review by furk4nyuksel — APPROVED** [review]
this is the best until keylo does the best

**Comment by EnesOkutan** [comment]
Is there some problems with some inline spaces, or is it just me?

For example:
in /win/editreg.py:

image

**Comment by orhun** [comment]
> Is there some problems with some inline spaces, or is it just me?
> 
> For example:
> in /win/editreg.py:
> 
> image

Set indent to tab (size of 4) and it'll fix itself.
I don't know why this happened but it is probably about the other indent settings you guys have been using. (Who uses 8 size instead of 4 anyway? -_-)
Did you see another indent issue somewhere else or is it just that file?

**Comment by EnesOkutan** [comment]
there is no problem in another file. 
Although this error is corrected in the editor, I don't understand why it looks like this here.

**Review by afk — APPROVED** [review]

**Pull request merged**
